main: io.github.aleksandarharalanov.poseidondiskfix.PoseidonDiskFix
version: 1.2.0
name: PoseidonDiskFix
author: Beezle
website: github.com/AleksandarHaralanov/project-poseidon-pre-b54aad06-creeper-disk-fix
description: Fixes creepers shot by skeletons not dropping music disks for servers running on Project Poseidon prior to Build 54aad06.